### PR TITLE
fix(core): Negative active time series cardnality due to missed increments

### PR DESCRIPTION
**Pull request by vishramachandran**
**Pull Request checklist**

- [x] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?

Added missing increments to activeTimeSeries count.

### CODE REVIEW

**Review by sherali42 — APPROVED** [review]
thanks @vishramachandran, looks good 👍

**Review by amolnayak311 — APPROVED** [review]
Thank @sherali42  for the lead and @vishramachandran for quick PR

**Review by yu-shipit — APPROVED** [review]
lgtm

**Review by yu-shipit — APPROVED** [review]
lgtm

**Pull request merged**
