### PR TITLE
Update "io.monix" % "monix" to 2.3.0

### PR DESCRIPTION
**Pull request by alexandru**
Updating to latest version, since the changes from 2.1.1 are significant.

### CODE REVIEW

**Comment by alexandru** [comment]
Build failed.

Is this normal or do you think it's because of the updated?

**Comment by velvia** [comment]
Hmm that's really weird.  I think the Travis build just hung.  Maybe we need more memory.  I kicked it again.  I'll try to run this locally though.

**Comment by velvia** [comment]
@alexandru OK, my local test run of `sbt core/test` hangs as well.  If you run this locally you should be able to observe the issue with the custom `SortedGroupByOperator` I talk about above.....   I ran `jstack` on the hung process and this is the suspect thread dump:

```
"pool-1-thread-1-ScalaTest-running-ReprojectorSpec" #11 prio=5 os_prio=31 tid=0x00007f862c919800 nid=0x5803 waiting on condition [0x00007000016d5000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007a9057140> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:353)
	at filodb.core.Iterators$ObservableIterator$$anonfun$2.apply(Iterators.scala:51)
	at filodb.core.Iterators$ObservableIterator$$anonfun$2.apply(Iterators.scala:51)
	at monix.reactive.internal.subscribers.ForeachSubscriber.onNext(ForeachSubscriber.scala:38)
	at monix.reactive.internal.subscribers.ForeachSubscriber.onNext(ForeachSubscriber.scala:27)
	at monix.reactive.internal.operators.MaterializeOperator$$anon$1.onNext(MaterializeOperator.scala:39)
	at monix.reactive.internal.operators.CollectOperator$$anon$1.onNext(CollectOperator.scala:47)
	at monix.reactive.internal.operators.ScanObservable$$anon$1.onNext(ScanObservable.scala:55)
	at monix.reactive.internal.operators.ConcatMapObservable$ConcatMapSubscriber$$anon$1.onNext(ConcatMapObservable.scala:140)
	at monix.reactive.internal.operators.ConcatMapObservable$ConcatMapSubscriber$$anon$1.onNext(ConcatMapObservable.scala:140)
	at monix.reactive.internal.operators.ConcatMapObservable$ConcatMapSubscriber$$anon$1.onNext(ConcatMapObservable.scala:140)
	at monix.reactive.internal.builders.IteratorAsObservable.monix$reactive$internal$builders$IteratorAsObservable$$fastLoop(IteratorAsObservable.scala:165)
	at monix.reactive.internal.builders.IteratorAsObservable.startLoop(IteratorAsObservable.scala:66)
	at monix.reactive.internal.builders.IteratorAsObservable.unsafeSubscribeFn(IteratorAsObservable.scala:45)
	at monix.reactive.internal.builders.IterableAsObservable.unsafeSubscribeFn(IterableAsObservable.scala:29)
	at monix.reactive.internal.operators.ConcatMapObservable$ConcatMapSubscriber.onNext(ConcatMapObservable.scala:135)
	at monix.reactive.internal.builders.IteratorAsObservable.monix$reactive$internal$builders$IteratorAsObservable$$fastLoop(IteratorAsObservable.scala:165)
	at monix.reactive.internal.builders.IteratorAsObservable.startLoop(IteratorAsObservable.scala:66)
	at monix.reactive.internal.builders.IteratorAsObservable.unsafeSubscribeFn(IteratorAsObservable.scala:45)
	at monix.reactive.internal.builders.IterableAsObservable.unsafeSubscribeFn(IterableAsObservable.scala:29)
	at monix.reactive.internal.operators.ConcatMapObservable.unsafeSubscribeFn(ConcatMapObservable.scala:71)
	at monix.reactive.internal.operators.ConcatMapObservable$ConcatMapSubscriber.onNext(ConcatMapObservable.scala:135)
	at monix.reactive.internal.builders.IteratorAsObservable.monix$reactive$internal$builders$IteratorAsObservable$$fastLoop(IteratorAsObservable.scala:165)
	at monix.reactive.internal.builders.IteratorAsObservable.startLoop(IteratorAsObservable.scala:66)
	at monix.reactive.internal.builders.IteratorAsObservable.unsafeSubscribeFn(IteratorAsObservable.scala:45)
	at monix.reactive.internal.builders.IterableAsObservable.unsafeSubscribeFn(IterableAsObservable.scala:29)
	at monix.reactive.internal.operators.ConcatMapObservable.unsafeSubscribeFn(ConcatMapObservable.scala:71)
	at monix.reactive.internal.operators.ConcatMapObservable$ConcatMapSubscriber.onNext(ConcatMapObservable.scala:135)
	at monix.reactive.internal.builders.IteratorAsObservable.monix$reactive$internal$builders$IteratorAsObservable$$fastLoop(IteratorAsObservable.scala:165)
	at monix.reactive.internal.builders.IteratorAsObservable.startLoop(IteratorAsObservable.scala:66)
	at monix.reactive.internal.builders.IteratorAsObservable.unsafeSubscribeFn(IteratorAsObservable.scala:45)
	at monix.reactive.internal.operators.ConcatMapObservable.unsafeSubscribeFn(ConcatMapObservable.scala:71)
	at monix.reactive.internal.operators.ScanObservable.unsafeSubscribeFn(ScanObservable.scala:40)
	at monix.reactive.Observable$$anon$5.unsafeSubscribeFn(Observable.scala:139)
	at monix.reactive.Observable$$anon$5.unsafeSubscribeFn(Observable.scala:139)
	at monix.reactive.Observable$class.foreach(Observable.scala:550)
	at monix.reactive.Observable$$anon$5.foreach(Observable.scala:136)
	at filodb.core.Iterators$ObservableIterator.<init>(Iterators.scala:51)
	at filodb.core.Iterators$RichObservable.toIterator(Iterators.scala:31)
	at filodb.core.store.ColumnStore$class.scanChunks(ColumnStore.scala:128)
	at filodb.core.store.InMemoryColumnStore.scanChunks(InMemoryColumnStore.scala:31)
	at filodb.core.store.ColumnStore$class.scanRows(ColumnStore.scala:142)
	at filodb.core.store.InMemoryColumnStore.scanRows(InMemoryColumnStore.scala:31)
	at filodb.core.reprojector.ReprojectorSpec$$anonfun$3.apply$mcV$sp(ReprojectorSpec.scala:80)
	at filodb.core.reprojector.ReprojectorSpec$$anonfun$3.apply(ReprojectorSpec.scala:65)
	at filodb.core.reprojector.ReprojectorSpec$$anonfun$3.apply(ReprojectorSpec.scala:65)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:422)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FunSpec.withFixture(FunSpec.scala:1626)
	at org.scalatest.FunSpecLike$class.invokeWithFixture$1(FunSpecLike.scala:419)
	at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431)
	at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSpecLike$class.runTest(FunSpecLike.scala:431)
	at filodb.core.reprojector.ReprojectorSpec.org$scalatest$BeforeAndAfter$$super$runTest(ReprojectorSpec.scala:19)
	at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
	at filodb.core.reprojector.ReprojectorSpec.runTest(ReprojectorSpec.scala:19)
	at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464)
	at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSpecLike$class.runTests(FunSpecLike.scala:464)
	at org.scalatest.FunSpec.runTests(FunSpec.scala:1626)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1626)
	at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468)
	at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSpecLike$class.run(FunSpecLike.scala:468)
	at filodb.core.reprojector.ReprojectorSpec.org$scalatest$BeforeAndAfter$$super$run(ReprojectorSpec.scala:19)
	at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
	at filodb.core.reprojector.ReprojectorSpec.org$scalatest$BeforeAndAfterAll$$super$run(ReprojectorSpec.scala:19)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
	at filodb.core.reprojector.ReprojectorSpec.run(ReprojectorSpec.scala:19)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)

```

If you have insights on how to fix `SortedGroupByOperator` (or can offer any suggestions to resolve this) would really appreciate it.  Thanks!

**Comment by velvia** [comment]
@alexandru sorry it is not `SortedGroupByOperator`, but rather `ObservableIterator` in Iterators.scala which attempts to get an Iterator out of an Observable by pushing elements to an ArrayBlockingQueue.  I'm sure there is a better way of doing what I'm trying to do..... however the Iterator is unfortunately required because eventually we will use Spark to do queries, and Spark requires an Iterator  :(

**Comment by alexandru** [comment]
Try replacing that asyncBoundary with a subscribeOn then.


On Wed, Jul 19, 2017, at 23:51, Evan Chan wrote:
> *@velvia* approved this pull request.


> @alexandru[1] thanks, the .asyncBoundary appears to have worked; Travis CI is happy.   Though I guess it is a slight waste -- doesn't asyncBoundary also use a queue? or a buffer at least.> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub[2], or mute the thread[3]. > 

Links:

  1. https://github.com/alexandru
  2. https://github.com/filodb/FiloDB/pull/147#pullrequestreview-51037152

**Comment by velvia** [comment]
@alexandru thanks, have a good vacation!

**Comment by velvia** [comment]
Thanks @alexandru it is merged, with the `.subscribeOn` suggestion you made

**Pull request merged**
