### PR TITLE
fix(job) handle null pointer in cardinality busting job

### PR DESCRIPTION
**Pull request by yu-shipit**
**Pull Request checklist**

- [ ] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?

**Current behavior :** (link exiting issues here : https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)

**New behavior :**

**BREAKING CHANGES**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

Breaking changes may include:
- Any schema changes to any Cassandra tables
- The serialized format for Dataset and Column (see .toString methods)
- Over the wire formats for Akka messages / case classes
- Changes to the HTTP public API
- Changes to query parsing / PromQL parsing

**Other information**:

### CODE REVIEW

**Comment by amolnayak311** [comment]
Why so many commits showing up? Can you rebase and push again?

**Comment by yu-shipit** [comment]
> Why so many commits showing up? Can you rebase and push again?

was based on integration branch. Just fixed it.

**Comment by amolnayak311** [comment]
What is the source of the  exception, can you please update the PR description to give some context?

**Comment by yu-shipit** [comment]
> What is the source of the exception, can you please update the PR description to give some context?

`
23/07/07 19:27:13 ERROR Executor: Exception in task 14.0 in stage 0.0 (TID 14)
java.lang.NullPointerException
	at filodb.cardbuster.PerShardCardinalityBuster.$anonfun$bustIndexRecords$2(PerShardCardinalityBuster.scala:88)
	at filodb.cardbuster.PerShardCardinalityBuster.$anonfun$bustIndexRecords$2$adapted(PerShardCardinalityBuster.scala:85)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:515)
	at monix.reactive.internal.builders.IteratorAsObservable.fastLoop(IteratorAsObservable.scala:146)
	at monix.reactive.internal.builders.IteratorAsObservable.startLoop(IteratorAsObservable.scala:61)
	at monix.reactive.internal.builders.IteratorAsObservable.unsafeSubscribeFn(IteratorAsObservable.scala:41)
	at monix.reactive.internal.operators.MapParallelUnorderedObservable.unsafeSubscribeFn(MapParallelUnorderedObservable.scala:61)
	at monix.reactive.Observable.$anonfun$completedL$1(Observable.scala:4414)
	at completedL @ filodb.cardbuster.PerShardCardinalityBuster.bustIndexRecords(PerShardCardinalityBuster.scala:104)
Collapse`

**Review by amolnayak311 — APPROVED** [review]

**Pull request merged**
