### PR TITLE
feat(core,memory): Don't free the native memory used by TimeSeriesPartition too soon.

### PR DESCRIPTION
**Pull request by broneill**
**Pull Request checklist**

- [x] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
- [x] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?

**Current behavior :**
Removing partitions can cause SEGVs.

**New behavior :**
Native memory is freed only after garbage collection.

### CODE REVIEW

**Comment by vishramachandran** [comment]
@broneill what is the effect of this change if there is plenty of heap space available, but we are running out of non-heap (native) space? 

If GC is deferred, allocation for new incoming partitions may fail. Is this right? Could you explain the behavior in such a scenario?

**Comment by vishramachandran** [comment]
@broneill I am not clear if this PR addresses the problem of readers being present (due to queries) at the time of freeing partition's (or shard's) native memory. 

Are we relying on the fact that the latency between removal of the partition to actual GC of the partition is sufficient for readers to finish their work on that partition's native memory ?

**Comment by broneill** [comment]
> @broneill what is the effect of this change if there is plenty of heap space available, but we are running out of non-heap (native) space?
> 
> If GC is deferred, allocation for new incoming partitions may fail. Is this right? Could you explain the behavior in such a scenario?

If partitions cannot be allocated, then the current behavior is to drop the data and try again later. I can add an explicit GC before this, to help reduce the likelihood of this happening.

**Comment by broneill** [comment]
> @broneill I am not clear if this PR addresses the problem of readers being present (due to queries) at the time of freeing partition's (or shard's) native memory.
> 
> Are we relying on the fact that the latency between removal of the partition to actual GC of the partition is sufficient for readers to finish their work on that partition's native memory ?

The readers will have a reference to the chunk map (OffheapLFSortedIDMap) indirectly through the thread-local reference to the shared lock state. The chunk map and the partition object are the same thing, and so the partition object remains non-reclaimable by the GC until after the readers finish.

**Pull request closed without merging**
