### PR TITLE
fix(memory): Fix DeltaDelta bug where slope(int) multiply overflowed

### PR DESCRIPTION
**Pull request by velvia**
**Pull Request checklist**

- [x] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
- [x] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?

**Current behavior :** (link exiting issues here : https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)

For some chunks encoded using Delta-Delta, there is a bug resulting from integer overflow where reading the chunk starting at a certain chunk index would lead to incorrect numbers being returned.  Basically the slope, which is a 32-bit integer, was multiplied by an integer and the result was overflow.

**New behavior :**

The slope calculation for DDV is now done using Long's so it won't overflow in the same way.

### CODE REVIEW

**Comment by velvia** [comment]
@broneill  because slope cannot be more than a 32-bit number, that is how it is stored.  DDV encoding ensures the slope is no more than 32 bits.  32bit x 32bit will not overflow a Long.

**Comment by broneill** [comment]
It looks a bit odd now, because before the types returned by the field extraction functions match the documentation. Why not just call toLong where necessary? At least it's consistent and doesn't give the odd impression that these functions can actually accept a long slope.

**Comment by velvia** [comment]
@broneill it's easier than doing it in every single place.  I guess I can change it the other way too.

**Comment by velvia** [comment]
@broneill changed to have toLong's conversion everywhere

**Pull request merged**
